// This script verifies that a minimal site contains only the barebones of a site.

import com.jcabi.w3c.ValidatorBuilder
import org.hamcrest.MatcherAssert
import org.hamcrest.Matchers

// Verifies that all the files were created
[
    'target/site/index.html'
].each {
    def file = new File(basedir, it)
    if (!file.exists()) {
        throw new IllegalStateException(
            "file ${file} doesn't exist"
        )
    }
}

// Acquires the sample HTML content
def html = new File(basedir, 'target/site/index.html').text

// Validates HTML 5
def htmlResponse = new ValidatorBuilder().html().validate(html)

MatcherAssert.assertThat(
    'There are errors',
    htmlResponse.errors(),
    Matchers.describedAs(htmlResponse.toString(), Matchers.hasSize(0))
)
MatcherAssert.assertThat(
    'There are warnings',
    htmlResponse.warnings(),
    Matchers.describedAs(htmlResponse.toString(), Matchers.hasSize(0))
)

// Verifies the skin info is included
// Footer link
assert html.contains( 'Rendered using <a href="https://github.com/Bernardo-MG/docs-maven-skin">Docs Maven Skin</a>' )
// Note in code
assert html.contains( 'Rendered using Docs Maven Skin' )
assert html.contains( 'Generated by Apache Maven Doxia' )

// Verifies the footer columns does not exist
assert !html.contains( '<dt>General Info</dt>' )
assert !html.contains( '<dt>Code</dt>' )
assert !html.contains( '<dt>Releases</dt>' )

// Verifies metadata is not included
assert !html.contains( '<meta name="description" content="Check the documentation for Basic Maven Project">' )
assert !html.contains( '<meta name="keywords" content="Maven, Java, library">' )
assert !html.contains( '<meta name="author" content="Bernardo Martínez Garrido" />' )

// Verifies Twitter Card metadata is not included
assert !html.contains( '<meta name="twitter:card" content="summary"/>' )
assert !html.contains( '<meta name="twitter:site" content="@bmg"/>' )
assert !html.contains( '<meta name="twitter:title" content="Simple site example &#x2013; library-maven-archetype-example"/>' )
assert !html.contains( '<meta name="twitter:description" content="Check the documentation for Basic Maven Project"/>' )

// Verifies that the main menus are not generated
assert !html.contains( '<li class="dropdown">' )

// Verifies that the footer menus are not generated
assert !html.contains( '<div id="navbar-footer" class="row">' )
assert !html.contains( '<dl class="dl-nav">' )
