// This script verifies that a minimal site contains only the barebones of a site.

import org.jsoup.Jsoup

// Verify all required files exist
def paths = [
    'target/site/index.html',
    'module/target/site/index.html'
]
def missing = paths.findAll { !new File(basedir, it).exists() }
if (missing) throw new IllegalStateException("Missing files: ${missing.join(', ')}")

// Check both root and module
paths.each { path ->
    def html = new File(basedir, path).text
    def body = Jsoup.parse(html).body()

    // Footer link
    assert body.select('footer #footer-info div').last().html().contains('Rendered using')

    // Comment presence
    assert html.contains('Rendered using Docs Maven Skin')
    assert html.contains('Generated by Apache Maven Doxia')
}

assert true
