// This script verifies that a minimal site contains only the barebones of a site.

import org.jsoup.Jsoup
import java.util.logging.Logger

// Acquires the sample HTML content
def html = new File(basedir, 'target/site/index.html').text
def htmlModule = new File(basedir, 'module/target/site/index.html').text

def htmlResponseModule = new ValidatorBuilder().html().validate(htmlModule)
MatcherAssert.assertThat(
    'There are errors',
    htmlResponseModule.errors(),
    Matchers.describedAs(htmlResponseModule.toString(), Matchers.hasSize(0))
)

htmlResponseModule.warnings().each{ value -> 
	logger.warning( value.toString() )
}

// Parses HTML
def parsed = Jsoup.parse(html)
def body = parsed.body()
def head = parsed.head()

// Verifies the skin info is included

// Footer link
def div = body.select( 'footer #footer-info div' ).last()
assert div.html().contains( 'Rendered using' )

// Comments before the head
assert html.contains( 'Rendered using Docs Maven Skin' )
assert html.contains( 'Generated by Apache Maven Doxia' )
