// This script verifies that a minimal site contains only the barebones of a site.

// The files to test are read
File index = new File( basedir, "target/site/index.html" )

// Verifies that all the files were created
assert index.exists()

// Acquires the sample HTML content
String html = index.getText()

// Verifies the skin info is included
// Footer link
assert html.contains( 'Rendered using <a href="https://github.com/Bernardo-MG/docs-maven-skin">Docs Maven Skin</a>' )
// Note in code
assert html.contains( 'Rendered using Docs Maven Skin' )
assert html.contains( 'Generated by Apache Maven Doxia' )

// Verifies the footer columns does not exist
assert !html.contains( '<dt>General Info</dt>' )
assert !html.contains( '<dt>Code</dt>' )
assert !html.contains( '<dt>Releases</dt>' )

// Verifies metadata is not included
assert !html.contains( '<meta name="description" content="Check the documentation for Basic Maven Project">' )
assert !html.contains( '<meta name="keywords" content="Maven, Java, library">' )
assert !html.contains( '<meta name="author" content="Bernardo Martínez Garrido" />' )

// Verifies Twitter Card metadata is not included
assert !html.contains( '<meta name="twitter:card" content="summary"/>' )
assert !html.contains( '<meta name="twitter:site" content="@bmg"/>' )
assert !html.contains( '<meta name="twitter:title" content="Simple site example &#x2013; library-maven-archetype-example"/>' )
assert !html.contains( '<meta name="twitter:description" content="Check the documentation for Basic Maven Project"/>' )
