// This script verifies that a simple site contains all the elements. Meaning that this
// test validates that all the common pieces of the site are generated when the Skin
// has all the data it requires.

// The files to test are read
File acquire = new File( basedir, "target/site/acquire.html" )
File index = new File( basedir, "target/site/index.html" )
File info = new File( basedir, "target/site/info.html" )
File reports = new File( basedir, "target/site/reports.html" )
File usage = new File( basedir, "target/site/usage.html" )

// Verifies that all the files were created
assert acquire.exists()
assert index.exists()
assert info.exists()
assert reports.exists()
assert usage.exists()

// Acquires the sample HTML content
String html = index.getText()

// Verifies the skin info is included
// Footer link
assert html.contains( 'Rendered using <a href="https://github.com/Bernardo-MG/docs-maven-skin">Docs Maven Skin</a>' )
// Note in code
assert html.contains( 'Rendered using Docs Maven Skin' )
assert html.contains( 'Generated by Apache Maven Doxia' )

// Verifies the footer columns exist
assert html.contains( '<dt>General Info</dt>' )
assert html.contains( '<dt>Code</dt>' )
assert html.contains( '<dt>Releases</dt>' )

// Verifies the favicon is included
assert html.contains( '<link href="./favicon.ico" rel="shortcut icon" type="image/x-icon" />' )

// Verifies metadata
assert html.contains( '<meta name="description" content="Check the documentation for Basic Maven Project">' )
assert html.contains( '<meta name="keywords" content="Maven, Java, library">' )
assert html.contains( '<meta name="author" content="Bernardo Martínez Garrido" />' )

// Verifies Open Graph metadata
assert html.contains( '<meta property="og:type" content="website"/>' )
assert html.contains( '<meta property="og:site" content="Simple site example &#x2013; library-maven-archetype-example"/>' )
assert html.contains( '<meta property="og:title" content="Simple site example &#x2013; library-maven-archetype-example"/>' )
assert html.contains( '<meta property="og:description" content="Check the documentation for Basic Maven Project"/>' )

// Verifies Twitter Card metadata
assert html.contains( '<meta name="twitter:card" content="summary"/>' )
assert html.contains( '<meta name="twitter:site" content="@bmg"/>' )
assert html.contains( '<meta name="twitter:title" content="Simple site example &#x2013; library-maven-archetype-example"/>' )
assert html.contains( '<meta name="twitter:description" content="Check the documentation for Basic Maven Project"/>' )

// Verifies the data in the navbar

// Verifies the project information is shown
assert html =~ /<small class="navbar-text">1\.0\.0 \([0-9]+-[0-9]+-[0-9]+\)<\/small>/
