// This script verifies that a complete site contains all the elements. Meaning that this
// test validates that all the common pieces of the site are generated when the Skin
// has all the data it requires.

import org.hamcrest.MatcherAssert
import org.hamcrest.Matchers

// Verifies that all the files were created
[
    'target/site/acquire.html',
    'target/site/index.html',
    'target/site/info.html',
    'target/site/reports.html',
    'target/site/usage.html'
].each {
    def file = new File(basedir, it)
    if (!file.exists()) {
        throw new IllegalStateException(
            "file ${file} doesn't exist"
        )
    }
}

// Acquires the sample HTML content
def html = new File(basedir, 'target/site/index.html').text

// Verified the heading is set
assert html.contains( '<header class="page-header">' )

// Verifies the skin info is included
// Footer link
assert html.contains( 'Rendered using <a href="https://github.com/Bernardo-MG/docs-maven-skin">Docs Maven Skin</a>' )
// Note in code
assert html.contains( 'Rendered using Docs Maven Skin' )
assert html.contains( 'Generated by Apache Maven Doxia' )

// Verifies the footer columns exist
assert html.contains( '<dt>General Info</dt>' )
assert html.contains( '<dt>Code</dt>' )
assert html.contains( '<dt>Releases</dt>' )

// Verifies the menus exist
assert html.contains( '<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Documentation <span class="chevron_toggleable fa fa-chevron-up" aria-hidden="true"></span></a>' )
assert html.contains( '<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Info and reports <span class="chevron_toggleable fa fa-chevron-up" aria-hidden="true"></span></a>' )

// Verifies the favicon is included
assert html.contains( '<link href="./favicon.ico" rel="shortcut icon" type="image/x-icon" />' )

// Verifies metadata
assert html.contains( '<meta name="description" content="Check the documentation for Basic Maven Project">' )
assert html.contains( '<meta name="keywords" content="Maven, Java, library">' )
assert html.contains( '<meta name="author" content="Bernardo Martínez Garrido" />' )

// Verifies Open Graph metadata
assert html.contains( '<meta property="og:type" content="website"/>' )
assert html.contains( '<meta property="og:site" content="Simple site example &#x2013; library-maven-archetype-example"/>' )
assert html.contains( '<meta property="og:title" content="Simple site example &#x2013; library-maven-archetype-example"/>' )
assert html.contains( '<meta property="og:description" content="Check the documentation for Basic Maven Project"/>' )

// Verifies Twitter Card metadata
assert html.contains( '<meta name="twitter:card" content="summary"/>' )
assert html.contains( '<meta name="twitter:site" content="@bmg"/>' )
assert html.contains( '<meta name="twitter:title" content="Simple site example &#x2013; library-maven-archetype-example"/>' )
assert html.contains( '<meta name="twitter:description" content="Check the documentation for Basic Maven Project"/>' )

// Verifies the data in the navbar

// Verifies the project information is shown
assert html =~ /<small class="navbar-text">1\.0\.0 \([0-9]+-[0-9]+-[0-9]+\)<\/small>/
