name: Artifact deployment

on:
  release:
    types: [created]

jobs:
  github:
    name: Github deployment
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-github-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
      packages: write

    steps:
    - name: Deploy to Github
      uses: bernardo-mg/maven-github-deployment-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        jdk: 17

  central:
    name: Central deployment
    runs-on: ubuntu-latest
    environment: deployment_central
    concurrency:
      group: deploy-central-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - name: Deploy
      uses: bernardo-mg/maven-signed-deployment-action@v1
      with:
        username: ${{ secrets.CENTRAL_USERNAME }}
        password: ${{ secrets.CENTRAL_TOKEN }}
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
        jdk: 17
