name: Maven Central Repository Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Check-out
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: releases
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Deploy
      run: mvn deploy -B -P deployment,deployment-release
