name: Artifact deployment

on:
  release:
    types: [created]

jobs:
  github:
    name: Github deployment
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-github-${{ github.ref }}
      cancel-in-progress: true
    permissions: 
      contents: read
      packages: write

    steps:
    - name: Deploy to Github
      uses: bernardo-mg/maven-github-deployment-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        jdk: 17

  ossrh:
    name: OSSRH deployment
    runs-on: ubuntu-latest
    environment: deployment_ossrh
    concurrency:
      group: deploy-ossrh-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - name: Deploy
      uses: bernardo-mg/maven-signed-deployment-action@v1
      with:
        username: ${{ secrets.OSSRH_USERNAME }}
        password: ${{ secrets.OSSRH_TOKEN }}
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
        jdk: 17