name: Testing and validation

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [ 8, 11, 14 ]

    steps:
    - name: Check-out
      uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v2.1.0
      with:
        java-version: ${{ matrix.jdk }}
        distribution: 'adopt'
    - name: Run all tests
      run: mvn clean verify
